services:
  redis:
    image: redis:alpine
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 15s
      timeout: 3s
      retries: 3
    volumes:
      - redis_data:/data
    networks:
      - drls-net

  grpc-server:
    build:
      context: ./go
    depends_on:
      - redis
    deploy:
      replicas: 3
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - drls-net

  grpc-test:
    build:
      context: ./go
    depends_on:
      redis:
        condition: service_healthy
    entrypoint: [ "go", "test", "./..." ]
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - drls-net

  express-server:
    build:
      context: ./express
    ports:
      - "5174:5174"
    depends_on:
      - grpc-server
    networks:
      - drls-net

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"  # Expose load balancer
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - grpc-server
    networks:
        - drls-net

networks:
  drls-net:

volumes:
  redis_data:
