services:
  redis:
    image: redis:alpine
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 15s
      timeout: 3s
      retries: 3
    volumes:
      - redis_data:/data
    networks:
      - drls-net

  grpc-server-1:
    build:
      context: ./go
    ports:
      - "50051:50051"
    depends_on:
      - redis
    environment:
      - GRPC_PORT=50051
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - drls-net

  grpc-server-2:
    build:
      context: ./go
    ports:
      - "50052:50052"
    depends_on:
      - redis
    environment:
      - GRPC_PORT=50052
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - drls-net

  grpc-server-3:
    build:
      context: ./go
    ports:
      - "50053:50053"
    depends_on:
      - redis
    environment:
      - GRPC_PORT=50053
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - drls-net

  grpc-test:
    build:
      context: ./go
    depends_on:
      redis:
        condition: service_healthy
    entrypoint: [ "go", "test", "./..." ]
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - drls-net

  express-server:
    build:
      context: ./express
    ports:
      - "5174:5174"
    depends_on:
      - grpc-server-1
    networks:
      - drls-net

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - grpc-server-1
      - grpc-server-2
      - grpc-server-3
    networks:
        - drls-net

networks:
  drls-net:

volumes:
  redis_data:
