clients: 25
rps_per_client: 10
duration_seconds: 30
grpc_target: "localhost:8080"
pattern: "burst"  # "steady", "burst", "ramp"

burst:
  size_multiplier: 2         # burstSize = rps_per_client * size_multiplier
  interval_ms: 2000          # interval between bursts (in milliseconds)

ramp:
  step: 1                    # how many RPS to increase per interval
  interval_ms: 2000          # time between RPS increases (in milliseconds)
